###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "The Holy Bible",
  "author": "Multiple",
  "url": "www.example.com",
  "likes": 10
}