###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/660329376de4bdb150fd628c

###
DELETE http://localhost:3001/api/persons/delete/660329076de4bdb150fd6289

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Homer Simpson",
  "number": "213243123"
}
