###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/66032aee5986a455d779dc67

### Error getting ID, mongo identifier format
GET http://localhost:3001/api/persons/5c41c90e84d891c15dfa3431

### Error getting ID, not mongo identifier format
GET http://localhost:3001/api/persons/5c41c90e84d891c15dfa34311

###
DELETE http://localhost:3001/api/persons/660329076de4bdb150fd6289

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Homer Simpson",
  "number": "123-123123"
}

###
PUT http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Bart Simpson",
  "number": "223-1123123"
}