###
GET http://localhost:3000/api/persons

###
GET http://localhost:3000/info

###
GET http://localhost:3000/api/persons/2

###
DELETE http://localhost:3000/api/persons/delete/1

###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
  "name": "New name",
  "number": "213243123"
}
